import { createElement } from '@lwc/engine-dom';
import HotelRooms from 'c/hotelRooms';

describe('c-hotel-rooms', () => {

    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    // it('TODO: test case generated by CLI command, please fill in test logic', () => {
    //     // Arrange
    //     const element = createElement('c-hotel-rooms', {
    //         is: HotelRooms
    //     });

    //     // Act
    //     document.body.appendChild(element);

    //     // Assert
    //     // const div = element.shadowRoot.querySelector('div');
    //     expect(1).toBe(1);
    // });

    it('Count no of hotelRoom components and compare', () => {
        // Arrange 
        const hotelRooms = createElement('c-hotel-rooms', {
            is: HotelRooms
        });
        // Act 
        document.body.appendChild(hotelRooms);
        debugger;
        // Assert 
        const allHotelRoomComponents = hotelRooms.shadowRoot.querySelectorAll('c-hotel-room');
        expect(allHotelRoomComponents.length).toBe(7);
    });

    it('Check the title of the lightning card', () => {
        // Arrange 
        const hotelRooms = createElement('c-hotel-rooms', {
            is: HotelRooms
        });
        // Act 
        document.body.appendChild(hotelRooms);
        // Assert 
        const lightningCardComp = hotelRooms.shadowRoot.querySelector('lightning-card');
        expect(lightningCardComp.title).toEqual('Hotel Rooms');
    });

    it('displays default selectedHotelRoom values', () => {
        // Arrange
        const hotelRooms = createElement('c-hotel-rooms', {
            is: HotelRooms
        });

        //Act
        document.body.appendChild(hotelRooms);

        //Assert
        const roomName = hotelRooms.shadowRoot.querySelector('.h1RoomName');
        const roomCapacity = hotelRooms.shadowRoot.querySelector('h3');

        expect(roomName.textContent).toBe('Room Name ');
        expect(roomCapacity.textContent).toBe('Room Capacity ');
    });

    it('updates selectedHotelRoom display on tileclick event', async () => {
        // Arrange
        const hotelRooms = createElement('c-hotel-rooms', {
            is: HotelRooms
        });
        // Act
        document.body.appendChild(hotelRooms);

        // Assert
        const mockRoom = { roomName: 'B-02', roomCapacity: '5' };
        const event = new CustomEvent('tileclick', {
            detail: mockRoom,
            bubbles: true,
            composed: true
        });

        //Instead of dispatching the event on the component, simulate it from an element inside the shadow DOM
        const div = hotelRooms.shadowRoot.querySelector('.classDiv');
        div.dispatchEvent(event);
    
        await Promise.resolve();

        const roomName = hotelRooms.shadowRoot.querySelector('.h1RoomName');
        const roomCapacity = hotelRooms.shadowRoot.querySelector('h3');

        console.log(roomName.textContent);
        console.log(roomCapacity.textContent);

        expect(roomName.textContent).toBe('Room Name B-02');
        expect(roomCapacity.textContent).toBe('Room Capacity 5');
    });


});